server:
  port: 7070
spring:
  datasource:
    url: jdbc:h2:mem:spring;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: test
    password: 123
  jpa:
    generate-ddl: false
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  sql:
    init:
      mode: embedded
      schema-locations: classpath:sql/schema.sql