server:
  port: 8080
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:https/certificate.p12
    key-store-password: 123456
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 147b7388f3f222a8a6cc
            client-secret: e74c289ab246d6dac1fc00c5790771d466ac3064