server:
  port: 9090
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:https/certificate.p12
    key-store-password: 123456
spring:
  datasource:
    url: jdbc:h2:mem:spring;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: test
    password: 123
    initialization-mode: embedded
    embedded-database-connection: h2
    schema:
      - classpath:sql/schema.sql
    data:
      - classpath:sql/data.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  jpa:
    database: h2
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none