server:
  port: 9090
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:https/certificate.p12
    key-store-password: 123456
security:
  oauth2:
    client:
      client-id: resourceserver
      client-secret: resourceserversecret
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token