server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:https/certificate.p12
    key-store-password: 123456
spring:
  datasource:
    url: jdbc:h2:mem:spring;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: test
    password: 123
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  sql:
    init:
      mode: embedded
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql