INSERT IGNORE INTO T_PRODUCT (ID, NAME, OWNER) VALUES ('1', 'beer', 'jack');
INSERT IGNORE INTO T_PRODUCT (ID, NAME, OWNER) VALUES ('2', 'candy', 'jack');
INSERT IGNORE INTO T_PRODUCT (ID, NAME, OWNER) VALUES ('3', 'chocolate', 'rose');
