server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:spring;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: test
    password: 123
    initialization-mode: embedded
    schema:
      - classpath:sql/schema.sql
    embeddedDatabaseConnection: h2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true